plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

require:
  - ./lib/rubocop/cop/apiwork/sort_attr_arguments.rb

Apiwork/SortAttrArguments:
  Enabled: true

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "spec/dummy/**/*"
    - "vendor/**/*"

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  SafeAutoCorrect: true

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/SafeNavigation:
  SafeAutoCorrect: true

# Disable delegate cop - causes issues with constant vs symbol
Rails/Delegate:
  Enabled: false

# Schema files use class constants, not strings
Rails/ReflectionClassName:
  Exclude:
    - "docs/playground/app/schemas/**/*"

# Disable symbol array cop - breaks validation logic
Style/SymbolArray:
  Enabled: false

# Disable HTTP positional arguments - conflicts with DSL syntax
Rails/HttpPositionalArguments:
  Enabled: false

# RSpec style preferences - disable subjective cops
RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

# Naming and style preferences
Naming/VariableNumber:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

# Lint exceptions for test constants
Lint/ConstantDefinitionInBlock:
  Enabled: false

# Allow optional boolean parameters for DSL flexibility
Style/OptionalBooleanParameter:
  Enabled: false

# Allow multiline block chains for readability
Style/MultilineBlockChain:
  Enabled: false

# Increase line length for readability
Layout/LineLength:
  Max: 150

# Allow more parameters for complex validations
Metrics/ParameterLists:
  Max: 8

# Allow empty else for explicit flow control
Style/EmptyElse:
  Enabled: false

# Allow unused method arguments for interface consistency
Lint/UnusedMethodArgument:
  Enabled: false

# Allow ineffective access modifier for self methods
Lint/IneffectiveAccessModifier:
  Enabled: false

# Allow duplicate method definitions in tests
Lint/DuplicateMethods:
  Enabled: false
