require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - 'spec/dummy/**/*'

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  SafeAutoCorrect: true

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

# Disable delegate cop - causes issues with constant vs symbol
Rails/Delegate:
  Enabled: false

# Disable symbol array cop - breaks validation logic
Style/SymbolArray:
  Enabled: false

# Disable HTTP positional arguments - conflicts with DSL syntax
Rails/HttpPositionalArguments:
  Enabled: false
