plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

require:
  - ./lib/rubocop/cop/apiwork/keyword_shorthand.rb
  - ./lib/rubocop/cop/apiwork/sort_hash.rb
  - ./lib/rubocop/cop/apiwork/sort_keywords.rb
  - ./lib/rubocop/cop/apiwork/sort_method_arguments.rb
  - ./lib/rubocop/cop/apiwork/sort_method_definition.rb

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "spec/dummy/**/*"

Apiwork/KeywordShorthand:
  Enabled: true

Apiwork/SortHash:
  Enabled: true
  ShorthandsFirst: true

Apiwork/SortKeywords:
  Enabled: true
  ShorthandsFirst: true
  Methods:
    - attribute
    - belongs_to
    - enum
    - field
    - has_many
    - has_one
    - param
    - type
    - union
    - variant

Apiwork/SortMethodArguments:
  Enabled: true
  Methods:
    - attr_accessor
    - attr_reader
    - attr_writer
    - delegate

Apiwork/SortMethodDefinition:
  Enabled: true

Layout/LineLength:
  Max: 150

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineHashKeyLineBreaks:
  Enabled: true

Style/KeywordParametersOrder:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/ReflectionClassName:
  Exclude:
    - "docs/playground/app/schemas/**/*"

Rails/HttpPositionalArguments:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false
