plugins:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

require:
  - ./lib/rubocop/cop/apiwork/sort_attr_arguments.rb
  - ./lib/rubocop/cop/apiwork/sort_keyword_arguments.rb
  - ./lib/rubocop/cop/apiwork/sort_hash_keys.rb
  - ./lib/rubocop/cop/apiwork/multiline_hash_pairs.rb
  - ./lib/rubocop/cop/apiwork/multiline_keyword_arguments.rb

AllCops:
  TargetRubyVersion: 3.2
  NewCops: disable
  SuggestExtensions: false
  Exclude:
    - "spec/dummy/**/*"
    - "vendor/**/*"

Apiwork/SortAttrArguments:
  Enabled: true

Apiwork/SortKeywordArguments:
  Enabled: true

Apiwork/SortHashKeys:
  Enabled: true

Apiwork/MultilineHashPairs:
  Enabled: true
  MinPairs: 3

Apiwork/MultilineKeywordArguments:
  Enabled: true
  Methods:
    - attribute
    - belongs_to
    - enum
    - field
    - has_many
    - has_one
    - param
    - type
    - union
    - variant

Style/KeywordParametersOrder:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Max: 150

Layout/FirstParameterIndentation:
  EnforcedStyle: align_parentheses

Layout/ParameterAlignment:
  EnforcedStyle: with_first_parameter

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true

Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
  AllowMultilineFinalElement: false

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/HashAlignment:
  Enabled: true
  EnforcedHashRocketStyle: key
  EnforcedColonStyle: key

Layout/MultilineHashBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineArrayBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Layout/MultilineMethodCallBraceLayout:
  Enabled: true
  EnforcedStyle: symmetrical

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  SafeAutoCorrect: true

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/SafeNavigation:
  SafeAutoCorrect: true

Style/SymbolArray:
  Enabled: false

Style/OptionalBooleanParameter:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/EmptyElse:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: comma

Naming/VariableNumber:
  Enabled: false

Naming/PredicatePrefix:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Lint/IneffectiveAccessModifier:
  Enabled: false

Lint/DuplicateMethods:
  Enabled: false

Rails/Delegate:
  Enabled: false

Rails/ReflectionClassName:
  Exclude:
    - "docs/playground/app/schemas/**/*"

Rails/HttpPositionalArguments:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/IndexedLet:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/MessageSpies:
  Enabled: false

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/DescribeClass:
  Enabled: false

RSpec/LeakyConstantDeclaration:
  Enabled: false

RSpec/RemoveConst:
  Enabled: false

RSpec/BeforeAfterAll:
  Enabled: false

RSpec/SpecFilePathFormat:
  Enabled: false

Layout/MultilineHashKeyLineBreaks:
  Enabled: true
