# frozen_string_literal: true

source 'https://rubygems.org'

# Use the Apiwork gem from parent directory
gemspec path: '../..'

# Rails
gem 'rails', '~> 8.0'

# Database
gem 'sqlite3', '~> 2.0'

# Testing
gem 'rspec-rails', '~> 6.0'
